//go:build !ignore_autogenerated

/*
Copyright 2026 BSSConnects. All rights reserved.

This file is part of Nawat and is proprietary and confidential.
Unauthorized copying, modification, distribution or use of this file, via any
medium, is strictly prohibited. Use is permitted only under the terms of a
written licence agreement with BSSConnects.

SPDX-License-Identifier: LicenseRef-BSSConnects-Proprietary
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleInstance) DeepCopyInto(out *ModuleInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleInstance.
func (in *ModuleInstance) DeepCopy() *ModuleInstance {
	if in == nil {
		return nil
	}
	out := new(ModuleInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModuleInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleInstanceList) DeepCopyInto(out *ModuleInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModuleInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleInstanceList.
func (in *ModuleInstanceList) DeepCopy() *ModuleInstanceList {
	if in == nil {
		return nil
	}
	out := new(ModuleInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModuleInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleInstanceSpec) DeepCopyInto(out *ModuleInstanceSpec) {
	*out = *in
	if in.Foo != nil {
		in, out := &in.Foo, &out.Foo
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleInstanceSpec.
func (in *ModuleInstanceSpec) DeepCopy() *ModuleInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(ModuleInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleInstanceStatus) DeepCopyInto(out *ModuleInstanceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleInstanceStatus.
func (in *ModuleInstanceStatus) DeepCopy() *ModuleInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(ModuleInstanceStatus)
	in.DeepCopyInto(out)
	return out
}
